name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-java:
    runs-on: ubuntu-latest    
    steps:
        # Setup
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          submodules: recursive
      - uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3
        with:
          java-version: 21
          distribution: temurin
          cache: 'gradle'        
      - uses: dafny-lang/setup-dafny-action@f2a62432e820c6b0519d308c440b88d7eee411e4
        with:
          dafny-version: "4.11.0"
      - name: Set DAFNY_HOME
        run: echo "DAFNY_HOME=$(dirname $(which dafny))" >> $GITHUB_ENV
        # Build
      - name: Gradle Build
        run: ./gradlew --no-daemon build -Prandomize=5
        # Report
      - name: Verification Logs (EVM)
        if: always()
        run: ./gradlew --no-daemon debug --args="build/logs/verify.csv"
      - name: Verification Logs (Proofs)
        if: always()
        run: ./gradlew --no-daemon debug --args="build/logs/test_*.csv"

